<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
use Illuminate\Support\Facades\DB;

return new class extends Migration {
  public function up(): void
  {
    Schema::create('sale_purchase_contracts', function (Blueprint $table) {
      $table->id();

      // =========================
      // Contract number (generated by system)
      // =========================
      $table->string('contract_number', 50)->unique(); // مثال: SP-2026-000001

      // =========================
      // Seller (البائع)
      // =========================
      $table->string('seller_name')->index();
      $table->enum('seller_entity_type', ['individual', 'company', 'sole_proprietorship'])->index();
      $table->string('seller_national_id', 20)->nullable()->index();
      $table->text('seller_address')->nullable();

      // =========================
      // Buyer (المشتري)
      // =========================
      $table->string('buyer_name')->index();
      $table->enum('buyer_entity_type', ['individual', 'company', 'sole_proprietorship'])->index();
      $table->string('buyer_national_id', 20)->nullable()->index();
      $table->text('buyer_address')->nullable();

      // =========================
      // Sold unit/property (بيانات المبيع)
      // =========================
      $table->string('unit_number', 100)->index();
      $table->text('unit_address');
      $table->decimal('unit_area_sqm', 10, 2)->nullable();
      $table->text('unit_description')->nullable();

      // =========================
      // Dates (تواريخ)
      // =========================
      $table->date('contract_date')->index();             // تاريخ تحرير العقد
      $table->date('delivery_date')->nullable()->index(); // تاريخ التسليم (اختياري)

      // =========================
      // Payment / Price (الماليات)
      // =========================
      $table->string('currency', 10)->default('EGP')->index();

      $table->decimal('total_price', 12, 2)->index();      // إجمالي الثمن
      $table->decimal('down_payment', 12, 2)->default(0);  // مقدم (افتراضي 0)

      // remaining_amount سيتم إضافته بعد إنشاء الجدول (Generated Column إن أمكن)
      // remaining_amount = total_price - down_payment

      $table->enum('payment_method', ['cash', 'bank_transfer', 'installments'])
        ->default('cash')
        ->index();

      // لو نظام أقساط (اختياري)
      $table->unsignedInteger('installments_count')->nullable();
      $table->decimal('installment_amount', 12, 2)->nullable();
      $table->date('first_installment_date')->nullable()->index();

      // =========================
      // Status / Notes
      // =========================
      $table->enum('status', ['draft', 'active', 'completed', 'cancelled'])
        ->default('active')
        ->index();

      $table->text('notes')->nullable();

      // =========================
      // Attachments (Word + Signed PDF)
      // =========================
      $table->string('contract_word_file')->nullable();              // storage path
      $table->string('contract_word_original_name')->nullable();
      $table->string('contract_word_mime', 80)->nullable();
      $table->unsignedBigInteger('contract_word_size')->nullable();

      $table->string('signed_pdf_file')->nullable();                 // storage path
      $table->string('signed_pdf_original_name')->nullable();
      $table->string('signed_pdf_mime', 80)->nullable();
      $table->unsignedBigInteger('signed_pdf_size')->nullable();

      // =========================
      // Audit
      // =========================
      $table->foreignId('created_by')->nullable()->constrained('users')->nullOnDelete();
      $table->foreignId('updated_by')->nullable()->constrained('users')->nullOnDelete();

      // =========================
      // Timestamps / Soft deletes
      // =========================
      $table->timestamps();
      $table->softDeletes();

      // =========================
      // Helpful composite indexes
      // =========================
      $table->index(['status', 'contract_date'], 'sp_status_contract_date_idx');
      $table->index(['seller_entity_type', 'buyer_entity_type'], 'sp_seller_buyer_entity_idx');
      $table->index(['payment_method', 'status'], 'sp_payment_status_idx');
    });

    /**
     * Add remaining_amount as GENERATED STORED column (if supported).
     * Fallback: add it as a normal decimal column if generated columns are not supported.
     */
    try {
      DB::statement("
        ALTER TABLE sale_purchase_contracts
        ADD COLUMN remaining_amount DECIMAL(12,2)
        AS (total_price - down_payment) STORED
      ");
    } catch (\Throwable $e) {
      // Fallback column (computed in app if DB doesn't support generated columns)
      Schema::table('sale_purchase_contracts', function (Blueprint $table) {
        $table->decimal('remaining_amount', 12, 2)->nullable()->after('down_payment');
      });
    }

    /**
     * Optional CHECK constraints (enforced on MySQL 8.0.16+; may be ignored on older versions).
     * Wrapped in try/catch so migration never fails if unsupported.
     */
    try {
      DB::statement("ALTER TABLE sale_purchase_contracts ADD CONSTRAINT chk_sp_total_price_nonneg CHECK (total_price >= 0)");
      DB::statement("ALTER TABLE sale_purchase_contracts ADD CONSTRAINT chk_sp_down_payment_nonneg CHECK (down_payment >= 0)");
      DB::statement("ALTER TABLE sale_purchase_contracts ADD CONSTRAINT chk_sp_down_payment_le_total CHECK (down_payment <= total_price)");
      DB::statement("ALTER TABLE sale_purchase_contracts ADD CONSTRAINT chk_sp_unit_area_nonneg CHECK (unit_area_sqm IS NULL OR unit_area_sqm >= 0)");
      DB::statement("ALTER TABLE sale_purchase_contracts ADD CONSTRAINT chk_sp_installments_count_pos CHECK (installments_count IS NULL OR installments_count > 0)");
      DB::statement("ALTER TABLE sale_purchase_contracts ADD CONSTRAINT chk_sp_installment_amount_nonneg CHECK (installment_amount IS NULL OR installment_amount >= 0)");
    } catch (\Throwable $e) {
      // Ignore if CHECK constraints are not supported/enforced
    }
  }

  public function down(): void
  {
    Schema::dropIfExists('sale_purchase_contracts');
  }
};
